[project]
authors = ["Marcel Stimberg <marcel.stimberg@sorbonne-universite.fr>"]
name = "online_bg_removal"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[pypi-dependencies]
norfair = ">=2.1.1,<3"

[dependencies]
imagecodecs = ">=2024.6.1,<2025"
imageio = ">=2.37.0,<3"
imageio-ffmpeg = ">=0.6.0,<0.7"
pandas = ">=2.2.3,<3"
psutil = ">=6.1.1,<7"
pylibtiff = ">=0.6.1,<0.7"
libtiff = ">=4.6.0,<5"
pyqtgraph = ">=0.13.7,<0.14"
pyside6 = ">=6.7.2,<7"
pyyaml = ">=6.0.2,<7"
scikit-image = ">=0.24.0"
trackpy = ">=0.6.4,<0.7"
watchdog = ">=6.0.0,<7"
python = ">=3.11"

[target.linux-64.dependencies]
qt6-gtk-platformtheme = ">=6.7.2,<7"

[feature.gpu]
platforms = ["linux-64", "win-64"]
channels = ["conda-forge"]

[feature.gpu.dependencies]
cupy = "*"
cuda-version = "12.*"

[feature.gpu.system-requirements]
cuda = "12"

[environments]
gpu = { features = ["gpu"] }
default = { features = [] }

[tasks]
gui = "python background_remover.pyw"
