[project]
name = "online-bg-removal"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "imagecodecs>=2024.1.1",
    "imageio>=2.37.0",
    "imageio-ffmpeg>=0.6.0",
    "norfair>=2.2.0",
    "pandas>=2.2.3",
    "psutil>=6.1.1",
    "pylibtiff>=0.6.1",
    "pyqtgraph>=0.13.7",
    "pyside6>=6.7,<6.8",
    "pyyaml>=6.0.2",    
    "scikit-image>=0.25.1",
    "trackpy>=0.6.4",
    "watchdog>=6.0.0",
]

[project.optional-dependencies]
gpu = [
    "cupy-cuda12x>=13.3.0",
]
yolo = [
    "cupy-cuda12x>=13.3.0",
    "ultralytics>=8.4.54",
]

[tool.pixi.workspace]
channels = ["nvidia/label/cuda-12.4.1", "nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64", "win-64", "osx-arm64"]

[tool.pixi.dependencies]
imageio = ">=2.37.0"
imageio-ffmpeg = ">=0.6.0"
pandas = ">=2.2.3"
psutil = ">=7.0.0"
pylibtiff = ">=0.6.1"
libtiff = ">=4.6.0"
pyqtgraph = ">=0.13.7"
pyside6 = ">=6.7,<6.8"
pyyaml = ">=6.0.2"
scikit-image = ">=0.25.2"
trackpy = ">=0.6.4"
watchdog = ">=6.0.0"
python = ">=3.12,<3.13"
rich = "<15"  # required by norfair
numpy = "<2"
imagecodecs = ">=2024.1.1"
tqdm = ">=4.67.1"

[tool.pixi.feature.tf.pypi-dependencies]
tensorflow = ">=2.11"

[tool.pixi.feature.tf.dependencies]
keras = ">=2.11"

[tool.pixi.activation.env]
TF_FORCE_GPU_ALLOW_GROWTH = "true"

[tool.pixi.target.unix.activation.env]
LD_LIBRARY_PATH = "$LD_LIBRARY_PATH:$CONDA_PREFIX/lib"

[tool.pixi.target.linux-64.dependencies]
qt6-gtk-platformtheme = ">=6.7.2,<7"

[tool.pixi.feature.pixi-gpu]
platforms = ["linux-64", "win-64"]

[tool.pixi.feature.pixi-gpu.dependencies]
cupy = ">=13.3.0"
cuda = {version = "*", channel="nvidia/label/cuda-12.4.1"}
pytorch = {version = "*", channel="pytorch"}
torchvision = {version = "*", channel="pytorch"}
pytorch-cuda = {version = "12.4.*", channel="pytorch"}

[tool.pixi.feature.pixi-gpu.system-requirements]
cuda = "12"

[tool.pixi.feature.pixi-yolo.dependencies]
ultralytics = "=8.4.62"

[tool.pixi.feature.pixi-yolo.pypi-dependencies]
tensorrt-cu12 =">=7.0.0,!=10.2.0,<11"
onnx = ">=1.12.0,<2.0.0"
onnxslim = ">=0.1.71"
onnxruntime-gpu = "*"

[tool.pixi.feature.pixi-yolo.pypi-options]
index-url = "https://pypi.nvidia.com"
extra-index-urls = ["https://pypi.org/simple"]


[tool.pixi.environments]
tf = ["tf"]
tf-gpu = ["tf", "pixi-gpu"]
gpu = ["pixi-gpu"]
yolo = ["pixi-gpu", "pixi-yolo"]

[tool.pixi.tasks]
gui = "python background_remover.pyw"