name: Test Project installation and run

on: [push, pull_request]

jobs:
    test-pixi:
        name: Test pixi install ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        
        steps:
        - name: Checkout repository
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        
        - name: Install pixi
          uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11  # v0.9.6
          with:
            cache: true

        - name: Run the GUI
          run: pixi run gui
          env:
            QT_QPA_PLATFORM: offscreen
            TEST_SHUTDOWN_GUI: 1
