name: Test Project with UV

on: [push, pull_request]

jobs:
    test-uv:
        name: Test uv install (${{ matrix.os }} / ${{ matrix.python-version }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-24.04, windows-2022, macos-13, macos-14]
                python-version: [3.11, 3.12]

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install Qt
          uses: jurplel/install-qt-action@v4
          with:
            version: 6.8.2
            aqtversion: '>=3.2.0'

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            enable-cache: true
            python-version: ${{ matrix.python-version }}
        
        - name: Install the project
          run: uv sync
        
        - name: Run the GUI
          run: uv run background_remover.pyw
          env:
            QT_QPA_PLATFORM: offscreen
            TEST_SHUTDOWN_GUI: 1

    test-pixi:
        name: Test pixi install ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-24.04, windows-2022, macos-13, macos-14]
        
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: Install pixi
          uses: prefix-dev/setup-pixi@v0.8.0
          with:
            cache: true

        - name: Run the GUI
          run: pixi run gui
          env:
            QT_QPA_PLATFORM: offscreen
            TEST_SHUTDOWN_GUI: 1

    test-pdm:
      name: Test pdm install ${{ matrix.os }} / ${{ matrix.python-version }})
      runs-on: ${{ matrix.os }}
      strategy:
          matrix:
              os: [ubuntu-24.04, windows-2022, macos-13, macos-14]
              python-version: [3.11, 3.12]
      
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          architecture: ${{ runner.arch }}
          python-version: ${{ matrix.python-version }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          setup-python: false
          aqtversion: '>=3.2.0'
      
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: pdm install --prod
          
      - name: Run the GUI
        run: pdm run gui
        env:
          QT_QPA_PLATFORM: offscreen
          TEST_SHUTDOWN_GUI: 1
